<?php

declare(strict_types=1);
/**
 * GEO Enhancer — AI Search Engine Optimization (Generative Engine Optimization).
 *
 * Targets ChatGPT, Perplexity, Gemini, Claude, and other LLM-powered search
 * engines by:
 *   1. Generating and serving /llms.txt (a robots.txt-like manifest for AI
 *      crawlers, proposed by llmstxt.org).
 *   2. Injecting AI-friendly meta tags into <head>:
 *      - <meta name="ai-content-optimizable" content="true">
 *      - <meta name="citation_optimized" content="true">
 *      - <meta name="faq_schema_boost" content="true">
 *   3. Boosting FAQ Schema markup so AI search engines prioritize citing
 *      the site's FAQ content.
 *
 * llms.txt format (simplified):
 *   # {Site Title}
 *
 *   > {Site Tagline / Description}
 *
 *   ## {Post Title 1}
 *   - [Post URL 1](/path/to/post-1): {Excerpt}
 *
 *   ## {Post Title 2}
 *   - [Post URL 2](/path/to/post-2): {Excerpt}
 *   ...
 *
 * @package Linked3
 * @subpackage Classes\SEO
 */

namespace Linked3\Classes\SEO;

if (!defined('ABSPATH')) {
    exit;
}

final class GEOEnhancer
{
    /** @var int Max posts to include in llms.txt (performance guard). */
    const LLMS_TXT_MAX_POSTS = 100;

    /** @var int Cache TTL for llms.txt content (1 hour). */
    const LLMS_TXT_CACHE_TTL = 3600;

    /**
     * Boot the GEO enhancer — register the /llms.txt request handler and
     * the wp_head meta injection.
     *
     * Called by SEOHooksRegistrar::register() during module boot.
     * Idempotent (add_action deduplicates).
     *
     * @return void
     */
    public static function init()
    : void {
        // Serve /llms.txt — we hook parse_request so we can short-circuit
        // before the theme template loader runs, avoiding a 404 on sites
        // without a physical llms.txt file.
        add_action('parse_request', [__CLASS__, 'handle_llms_txt_request']);

        // Inject AI-friendly meta tags into <head> on public pages.
        add_action('wp_head', [__CLASS__, 'inject_ai_meta'], 20);

        // Boost FAQ schema — runs after SEO_Hooks_Registrar::output_schema_markup
        // (priority 10) so we can augment the FAQ JSON-LD.
        add_filter('linked3/schema/faq', [__CLASS__, 'boost_faq_schema'], 10, 2);
    }

    /**
     * Generate the llms.txt content from published posts.
     *
     * @return string The llms.txt manifest (plain text).
     */
    public static function generate_llms_txt() : mixed {
        // Check for cached content first.
        $cached = get_transient('linked3_llms_txt_cache');
        if (is_string($cached) && $cached !== '') {
            return $cached;
        }

        $lines = [];

        // Header: site title + tagline.
        $lines[] = '# ' . wp_strip_all_tags(get_bloginfo('name'));
        $lines[] = '';
        $desc = wp_strip_all_tags(get_bloginfo('description'));
        if ($desc) {
            $lines[] = '> ' . $desc;
            $lines[] = '';
        }

        // Fetch published posts (most recent first, capped for performance).
        $posts = get_posts([
            'numberposts'      => self::LLMS_TXT_MAX_POSTS,
            'post_type'        => 'post',
            'post_status'      => 'publish',
            'orderby'          => 'date',
            'order'            => 'DESC',
            'suppress_filters' => false,
        ]);

        if (empty($posts)) {
            $lines[] = '(No published posts yet.)';
        } else {
            foreach ($posts as $p) {
                $lines[] = '## ' . wp_strip_all_tags($p->post_title);
                $url = get_permalink($p);
                $excerpt = self::extract_excerpt($p);
                $lines[] = '- [' . $url . '](' . $url . '): ' . $excerpt;
                $lines[] = '';
            }
        }

        // Footer: generation timestamp.
        $lines[] = '---';
        $lines[] = '# Generated by Linked3 AI at ' . gmdate('Y-m-d H:i:s') . ' UTC';

        $content = implode("\n", $lines);

        // Cache for 1 hour.
        set_transient('linked3_llms_txt_cache', $content, self::LLMS_TXT_CACHE_TTL);

        return $content;
    }

    /**
     * Handle the /llms.txt request — serve the generated content with the
     * correct text/plain content type.
     *
     * @param \WP $wp The WordPress request object.
     * @return void
     */
    public static function handle_llms_txt_request(WP $wp)
    : void {
        // Defensive: only serve on the frontend, never in admin or AJAX.
        if (is_admin() || (defined('DOING_AJAX') && DOING_AJAX) || (defined('REST_REQUEST') && REST_REQUEST)) {
            return;
        }

        // Check the request path — $_SERVER['REQUEST_URI'] is the most
        // reliable across permalink configurations.
        $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';
        $path = wp_parse_url($uri, PHP_URL_PATH);
        if ($path === null) {
            return;
        }

        // Normalize: trim query string, lowercase for comparison.
        $path = rtrim($path, '/');

        // Match /llms.txt exactly (case-insensitive path).
        if (strtolower($path) !== '/llms.txt') {
            return;
        }

        // Read the stored content (regenerate if missing).
        $content = (string) get_option(LINKED3_OPTION_PREFIX . 'llms_txt_content', '');
        if ($content === '') {
            $content = self::generate_llms_txt();
            update_option(LINKED3_OPTION_PREFIX . 'llms_txt_content', $content);
            update_option(LINKED3_OPTION_PREFIX . 'llms_txt_last_gen', time());
        }

        // Serve with text/plain content type.
        if (!headers_sent()) {
            header('Content-Type: text/plain; charset=utf-8');
            header('Cache-Control: public, max-age=' . self::LLMS_TXT_CACHE_TTL);
            header('X-Linked3: llms.txt');
        }

        printf('%s', $content); // text/plain, no HTML.

        // Exit cleanly so the theme template loader does not run.
        exit;
    }

    /**
     * Inject AI-friendly meta tags into <head>.
     *
     * These tags signal to AI crawlers that the content is:
     *   - ai-content-optimizable: OK to use for training/inference.
     *   - citation_optimized: Content is structured for citation.
     *   - faq_schema_boost: FAQ content is prioritized for AI search.
     *
     * @return void
     */
    public static function inject_ai_meta()
    : void {
        // Only on public, singular pages — not on admin, feeds, or search.
        if (is_admin() || is_feed() || is_search() || is_404()) {
            return;
        }

        $settings = self::get_settings();

        if (!empty($settings['llms_txt_enabled'])) {
            echo '<meta name="ai-content-optimizable" content="true">' . "\n";
            echo '<link rel="llms-txt" href="' . esc_url(home_url('/llms.txt')) . '">' . "\n";
        }
        if (!empty($settings['citation_optimized'])) {
            echo '<meta name="citation_optimized" content="true">' . "\n";
        }
        if (!empty($settings['faq_schema_boost'])) {
            echo '<meta name="faq_schema_boost" content="true">' . "\n";
        }

        // Auto AI summary: signal to AI crawlers that the page has a summary.
        if (!empty($settings['auto_ai_summary']) && is_singular()) {
            $summary = self::generate_ai_summary();
            if ($summary) {
                echo '<meta name="ai-summary" content="' . esc_attr($summary) . '">' . "\n";
            }
        }
    }

    /**
     * Boost FAQ schema markup so AI search engines prioritize citing it.
     *
     * @param array $faq  The FAQ JSON-LD array.
     * @param int   $post_id The post ID.
     * @return array The (possibly augmented) FAQ JSON-LD.
     */
    public static function boost_faq_schema(array $faq, int $post_id) : mixed     {
        $settings = self::get_settings();
        if (empty($settings['faq_schema_boost'])) {
            return $faq;
        }

        // Add a "citation_boost" flag to each FAQ entry so AI crawlers
        // know this content is optimized for citation.
        if (is_array($faq) && isset($faq['mainEntity'])) {
            foreach ($faq['mainEntity'] as &$entity) {
                if (is_array($entity)) {
                    $entity['citation_boost'] = true;
                }
            }
        }

        return $faq;
    }

    /**
     * Get the GEO settings (with defaults).
     *
     * @return array
     */
    public static function get_settings() : mixed {
        $defaults = [
            'llms_txt_enabled'    => true,
            'auto_ai_summary'     => true,
            'citation_optimized'  => true,
            'faq_schema_boost'    => true,
        ];
        $stored = (array) get_option(LINKED3_OPTION_PREFIX . 'geo_settings', []);
        return array_merge($defaults, $stored);
    }

    /**
     * Extract a clean excerpt for llms.txt from a post.
     *
     * @param \WP_Post $post
     * @return string Max 160 chars, no HTML, no newlines.
     */
    private static function extract_excerpt(WP_Post $post) : mixed     {
        $text = $post->post_excerpt;
        if (!$text) {
            $text = wp_trim_words(wp_strip_all_tags($post->post_content), 30, '');
        }
        $text = preg_replace('/\s+/', ' ', $text);
        $text = trim($text);
        if (strlen($text) > 160) {
            $text = substr($text, 0, 157) . '...';
        }
        return $text;
    }

    /**
     * Generate a short AI-friendly summary for the current singular post.
     *
     * Uses the post excerpt if available, otherwise the first 2 sentences.
     *
     * @return string Empty string if no summary could be extracted.
     */
    private static function generate_ai_summary() : mixed {
        $post = get_post();
        if (!$post) {
            return '';
        }

        $text = $post->post_excerpt;
        if ($text) {
            return wp_strip_all_tags($text);
        }

        // Fall back to first 2 sentences of the content.
        $content = wp_strip_all_tags($post->post_content);
        $content = preg_replace('/\s+/', ' ', $content);
        $content = trim($content);

        // Split on sentence boundaries (handles . ! ? both ASCII and fullwidth).
        $sentences = preg_split('/(?<=[.。!?！？])\s+/', $content, 3, PREG_SPLIT_NO_EMPTY);
        if (!empty($sentences)) {
            $summary = implode(' ', array_slice($sentences, 0, 2));
            if (strlen($summary) > 200) {
                $summary = substr($summary, 0, 197) . '...';
            }
            return $summary;
        }

        return '';
    }
}
